import 'https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/p5.js';
import 'https://cdnjs.cloudflare.com/ajax/libs/matter-js/0.18.0/matter.min.js';
var opacity = 10;
var rainbowMode = false;
var myColor = [0, 255, 255, opacity];
var particleMode = false;
var inc = 0.1;
let cols, rows;
let scl = 20;
let zoff = 0;
let fr;
let particles = [];
let flowfield = [];
let pixels = [];
var inView = true;
var isSetup = false;
var numParticles = 500;
var delta = 1;
var z = 1;
var stopAnimation = false;
let particleOpacity = 255;
let flowOpacity = 10;
var rainbowInterval;
// Add event listeners to the radio buttons
const particleRadio = document.getElementById('particleRadio');
const rainbowToggle = document.getElementById('rainbowToggle');
document.getElementById('flowRadio').checked = true;
rainbowToggle.checked = false;
particleRadio.checked = false;
